package com.app.ledger.constants;

/**
 * @author jaswin.shah
 * @version $Id: MessageConstants.java, v 0.1 2021-06-21 07:56 AM jaswin.shah Exp $$
 */
public interface MessageConstants {

    String REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";

    String BANK_NAME_ABSENT = "BANK_NAME_ABSENT";

    String BANK_CODE_ABSENT = "BANK_CODE_ABSENT";

    String BANK_BRANCH_ABSENT = "BANK_BRANCH_ABSENT";

    String BANK_CITY_ABSENT = "BANK_CITY_ABSENT";

    String BANK_PIN_CODE_ABSENT = "BANK_PIN_CODE_ABSENT";

    String BRANCH_ALREADY_EXIST = "BRANCH_ALREADY_EXIST";

    String CUSTOMER_ALREADY_REGISTERED_WITH_THIS_NAMES = "CUSTOMER_ALREADY_REGISTERED_WITH_THIS_NAMES";

    String INVALID_REQUEST = "INVALID_REQUEST";

    String LOAN_IS_CLOSED = "LOAN _IS_CLOSED";

    String AMOUNT_INVALID = "AMOUNT_INVALID";

    String EMAIL_MANDATORY = "EMAIL_MANDATORY";

    String MOBILE_MANDATORY = "MOBILE_MANDATORY";

    String FIRST_NAME_MANDATORY = "FIRST_NAME_MANDATORY";

    String LAST_NAME_MANDATORY = "LAST_NAME_MANDATORY";

    String BANK_NOT_REGISTERED = "BANK_NOT_REGISTERED";

    String NO_PRODUCTS_SPECIFIED = "NO_PRODUCTS_SPECIFIED";

    String INVALID_REQUEST_FEW_PRODUCTS_ALREADY_REGISTERED = "INVALID_REQUEST_FEW_PRODUCTS_ALREADY_REGISTERED";

    String SUCCESS = "SUCCESS";

    String DURATION_NOT_SUPPORTED_BY_LOAN_PRODUCT = "DURATION_NOT_SUPPORTED_BY_LOAN_PRODUCT";

    String PRINCIPAL_CAN_NOT_BE_ZERO = "PRINCIPAL_CAN_NOT_BE_ZERO";

    String LOAN_PRODUCT_INVALID = "LOAN_PRODUCT_INVALID";

    String INVALID_PRODUCT = "INVALID_PRODUCT";

    String INVALID_BRANCH = "INVALID_BRANCH";

    String UNREGISTERED_CUSTOMER = "UNREGISTER_CUSTOMER";

    String LOAN_ALREADY_APPROVED = "LOAN_ALREADY_APPROVED";

    String LOAN_ALREADY_REJECTED = "LOAN_ALREADY_REJECTED";

    String LOAN_ALREADY_UNDER_REVIEW = "LOAN_ALREADY_UNDER_REVIEW";

    String LOAN_ALREADY_DISBURSED = "LOAN_ALREADY_DISBURSED";

    String LOAN_NOT_REVIEWED = "LOAN_REQUEST_NOT_REVIEWED";

    String LOAN_REQUEST_NOT_APPROVED = "LOAN_REQUEST_NOT_APPROVED";


}
